name: Ejecucion Diaria Bot

on:
  schedule:
    # Esto es a las 10:00 AM hora Colombia (13:00 UTC)
    - cron: '0 13 * * *'
  workflow_dispatch: # Esto te da un botón para probarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Requests
        run: pip install requests

      - name: Correr Bot
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python bot.py
